initial commit for material chips
Applib-OpenHarmony/Material_UI_Chips pull request #2
Opened 2022-06-23 05:47 UTC by enigmij

Signed-off-by: unknown <ritwij3000@gmail.com>

2022-06-24 06:33 UTC, samuel-abhishek requested changes

2022-06-24 06:33 UTC, samuel-abhishek commented on README.md
> +# Material_Chip
Test report will be added as an artifact during the github release. Please remove it from the code repo.

2022-06-24 06:33 UTC, samuel-abhishek commented on README.md
> +### -Input Chip
Add a online description about each chip type.

2022-06-24 06:33 UTC, samuel-abhishek commented on README.md
> +/blob/main/LICENSE), please enjoy and participate in open source freely.
Extra space got added, therefore the URL is not linkified. Please check and handle.

2022-06-24 06:33 UTC, samuel-abhishek commented on materialchips/src/main/ets/components/MainPage/EditChip.ets
> +  @State Rad: number= 0
Use meaningful and understandable variable names.

2022-06-27 06:52 UTC, samuel-abhishek requested changes

2022-06-27 06:52 UTC, samuel-abhishek commented on materialchips/src/main/ets/components/MainPage/ActionChip.ets
> +    constructor(text: string | Resource) {
Include the chiptext also in parent class. Child class not required in this scenario. Do these changes for other chip types as well.

2022-06-27 06:52 UTC, samuel-abhishek commented on materialchips/src/main/ets/components/MainPage/ChoiceChip.ets
> +  @State Delete: number= 1
Please follow variable naming conventions.

2022-06-27 06:52 UTC, samuel-abhishek commented on materialchips/src/main/ets/components/MainPage/FilterChip.ets
> +
Format the code by Ctrl+Alt+L

2022-06-27 06:52 UTC, samuel-abhishek commented on README.md
> +In sets that contain at least two options, choice chips represent a single selection.
Please update the Readme as per the latest changes

2022-06-28 05:45 UTC, archanaatr reviewed
please check the comments

2022-06-28 05:45 UTC, archanaatr commented on materialchips/package.json
> +  "name": "@ohos/materialchips",
follow the library naming rules shared... Update it to @ohos/material-chips

2022-06-28 05:45 UTC, archanaatr commented on package.json
> +    "@ohos/materialchips": "file:./materialchips"
remove the chip lib dependency from the main file

2022-06-28 05:45 UTC, archanaatr commented on entry/package.json
> +    "@ohos/materialchips": "file:./materialchips"
change the lib name to material-chips

2022-06-28 05:45 UTC, archanaatr commented on entry/src/main/ets/MainAbility/app.ets
> +export default {
Add copyright in all the ets files

2022-06-28 05:45 UTC, archanaatr commented on materialchips/src/main/ets/components/MainPage/InputChip.ets
> +  @State delete: number= 1
format all the etc files . Open each file and perform Ctrl + Alt + L

2022-06-28 05:45 UTC, archanaatr commented on materialchips/src/main/ets/components/MainPage/InputChip.ets
> +        Image(this.model.getImage())
Add validation of null and undefined values on model. Recheck and add for all such case

2022-06-28 05:45 UTC, archanaatr commented on materialchips/src/main/ets/components/MainPage/InputChip.ets
> +    private textSize: number= 20
Mark all dimentions as vp and text sizes as fp

2022-06-28 05:45 UTC, archanaatr commented on materialchips/src/main/ets/components/MainPage/EditChip.ets
> +  @State Delete: number= 0
variable naming convention to be followed

2022-06-28 05:45 UTC, archanaatr commented on materialchips/src/main/ets/components/MainPage/EditChip.ets
> +                left: this.Delete * 12,
check to add as vp

2022-06-29 04:45 UTC, samuel-abhishek commented on README.md
> +    this.filterchip1.setText("Op1").setTextSize('20vp')
use "fp" for textSize/fontSize and for other use "vp"

2022-06-29 04:49 UTC, samuel-abhishek commented on entry/package.json
> +  "dependencies": {}
The lib dependency must be present here i.e entry's package.json. Remove the dependency from project's package.json

2022-06-30 07:01 UTC, merged